name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradle build
        working-directory: ./LunchLine
        run: chmod +x ./gradlew
      - name: Build the app
        working-directory: ./LunchLine
        run: ./gradlew build --no-daemon
