name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x ./HelloFigma/gradlew && ./HelloFigma/gradlew build
      - name: Build the app
        run: ./HelloFigma/gradlew build
